### PR TITLE
Add ability to mock requests from tests

### PR DESCRIPTION
**Pull request by superchris**

### CODE REVIEW

**Comment by dima117** [comment]
Hi,

Why you want to implement request stubs by browser instead using the existing library like [Sinon.js](http://sinonjs.org/releases/v4.5.0/fake-xhr-and-server)?

**Comment by superchris** [comment]
I thought it was a interesting feature of puppeteer to be able to use. This way we can have code that calls the fetch api provided by the browser and stub the request at the browser level. Perhaps that could be done with sinon as well.

**Comment by dima117** [comment]
Hello!

I'm sorry for the late reply.

I think that it is not necessary to add this functionality to the `mocha-headless-chrome`, since this is not in its area of responsibility. For example, if the tests depend on the `mocha-headless-chrome` API, then they can not be run without a `mocha-headless-chrome` (for example, in a browser).

Can you give any reason why the mocks of request should be added to the `mocha-headless-chrome`?

**Comment by dima117** [comment]
Since I still do not see any reason to implement your proposal, I will close this PR. Feel free to reopen it, if necessary.

**Pull request closed without merging**
