### PR TITLE
Add option to run test suite in incognito mode

### PR DESCRIPTION
**Pull request by lfairy**
In incognito mode, Chrome doesn't write any user data to disk. This can lead to significant speedups with test suites that use features like IndexedDB.

Note that when incognito is enabled, this will open two windows (one incognito and one non-incognito). I couldn't figured out how to suppress this behavior. It should be harmless though.

### CODE REVIEW

**Comment by lfairy** [comment]
I changed the short option to `-n`, to avoid confusion with the `-i`/`--invert` option in Mocha. (Also the keyboard shortcut for incognito mode is Ctrl-Alt-N.)

**Comment by dima117** [comment]
Hi,

you can launch chrome with `--incognito` argument. Is it solve your problem?

```
mocha-headless-chrome -f test.html -a incognito
```

**Comment by lfairy** [comment]
@dima117 Unfortunately, `-a incognito` doesn't work.

Consider the following test page:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Mocha Tests</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="node_modules/mocha/mocha.css">
  </head>
  <body>
    <div id="mocha"></div>
    <script src="node_modules/mocha/mocha.js"></script>
    <script>
      mocha.setup('bdd');
      it('test', function (done) {
        this.timeout(0);
        // Paint the background red to show where the test is running
        document.body.style.backgroundColor = 'red';
        setTimeout(done, 30 * 1000);
      });
      mocha.run();
    </script>
  </body>
</html>
```

If I run it with `node lib/cli.js -f test.html -a no-sandbox -a incognito --visible`, then I see the tests run in the normal window, not the incognito window.

But when I run it with `node lib/cli.js -f test.html -a no-sandbox -n --visible` instead, then it runs in the incognito window as expected.

**Comment by dima117** [comment]
I'm against adding an additional parameter, because this is a change of the public interface and it complicates the support. Will it suit you if I do the test run in single window (without creating a new one)?

**Comment by dima117** [comment]
I was fixed the promlem and publish new package v2.0.1.
Now the `--incognito` parameter works correctly.

**Pull request closed without merging**
